### ISSUE TITLE
MouseWheel bug

### ISSUE THREAD

**Issue by lbensaad** [caoym/WinRobot#1]
WinRobot.mouseWheel() moves in the opposit direction of java's Robot.mouseWheel

Java mouseWheel says:
@param wheelAmt  number of "notches" to move the mouse wheel
     \*                  **Negative** values indicate movement up/**away** from the user,
     \*                  **positive** values indicate movement down/**towards** the user.
see the docs here: https://docs.oracle.com/javase/7/docs/api/java/awt/Robot.html#mouseWheel(int)
but you are using SendInput and MSDN says:
A **positive** value indicates that the wheel was rotated forward, **away** from the user; 
a **negative** value indicates that the wheel was rotated backward, **toward** the user
see mousData here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms646273(v=vs.85).aspx

so your java WinRobot should pass -wheelAmt to the native library

Many thanks

**Comment by caoym** [comment]
fixed by lbensaad

**Comment by caoym** [comment]
fixed by lbensaad
