### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Toadstooliv** [caoym/WinRobot#10]
Hello,
I'm trying to use this in a project i'm working on but when I try to compile i get these errors

Severity    Code    Description Project File    Line    Suppression State
Error   C2664   'DWORD ChangeAppIDLaunchACL(LPTSTR,LPTSTR,BOOL,BOOL,DWORD)': cannot convert argument 1 from 'const TCHAR _' to 'LPTSTR' WinRobotHost    c:\users\_****\documents\winrobot\jni\winrobothost\winrobothost.cpp 168 

Severity    Code    Description Project File    Line    Suppression State
Error   C2664   'DWORD ChangeAppIDAccessACL(LPTSTR,LPTSTR,BOOL,BOOL,DWORD)': cannot convert argument 1 from 'const TCHAR _' to 'LPTSTR' WinRobotHost    c:\users\_****\documents\winrobot\jni\winrobothost\winrobothost.cpp 172 

This is on a machine running windows 10

Thanks in advance for your help

**Comment by caoym** [comment]
fixed
