### ISSUE TITLE
怎么截到的是登陆前的图啊

### ISSUE THREAD

**Issue by ShayneC** [caoym/WinRobot#11]
我已经是登陆后的界面了，这时候调用截图方法，截到的图是登陆界面的图，并且是用户名或密码不正确的那个界面。

**Comment by caoym** [comment]
你是指Winlogon界面吧，只要处在Winlogon界面时调用截图方法就行了。如果要做测试，可以设置定时时间，比如sleep五秒后截图，并在五秒内切换到登录界面。如果是需要实现电脑启动后即开始截图，需要写个程序，并注册成windows服务且设置为开机自动启动，这样就可以通过此服务进行截图

希望以上能帮到你

**Comment by ShayneC** [comment]
报密码错误，登陆不进去，这是什么原因啊？

**Comment by caoym** [comment]
能帮问题描述得更清楚些吗？

**Comment by caoym** [comment]
哦，我理解错你的问题了。
现在的问题是登录成功后，截图到的还是之前的界面吗？

**Comment by ShayneC** [comment]
是通过远程桌面登陆后操作的 ，我是管理员账户登陆的。之前用Robot 截图是没有问题的   用WinRobot 截图时出现的这个问题。  我用java 写的， 我把WinRobot.jar 放到我工程中直接调的。  机器是64 位 win7

**Comment by caoym** [comment]
通过远程桌面登录的话，实际上Windows创建了一个新的session，而当前物理机桌面还是停留在登录界面，WinRobot的GetActiveConsoleSession方法，只能获取到当前控制台（物理机上屏幕上显示的桌面）session，不能获取远程桌面的session，所以你截到的图会一直是登录界面。

**Comment by caoym** [comment]
而Robot 不同的是，它总是截当前程序所处的session，所以在远程桌面的时候，截到的是远程桌面的图像，但这就导致它截不到登录界面，因为登录界面处在不能session下。

**Comment by caoym** [comment]
如果你确实有这种需求，需要在远程桌面的时候工作，可以参考GetActiveConsoleSession增加类似GetSession(id)的方法，获取任意指定的session图像。

**Comment by ShayneC** [comment]
如果物理机没有显示器，还能截到登录后的界面吗？之前用原生的robot 截图，如果没有显示器的话，截到的是黑屏。不知道winrobot 能不能截到？ 多谢耐心提供帮助，多谢。

**Comment by caoym** [comment]
我记得没有显示器也能截到图像，可以试一下
