### ISSUE TITLE
Win XP 和 Win 7 截屏性能差别较大

### ISSUE THREAD

**Issue by Anudorannador** [caoym/WinRobot#9]
```
// get screen image data(with stream read)
CComQIPtr<ISequentialStream> pStream = pUnk;
char buf[1024];
ULONG cbBuffer  = 0 ;
while (pStream->Read(buf,sizeof(buf),&cbBuffer) == S_OK ){
    //  do something
}
```

这个函数在XP系统上非常慢，100ms一帧，但是在Windows 7 上性能很好，能达到10ms一帧。请问这是为什么？

**Comment by caoym** [comment]
在WinRobot代码上XP和Win7并没有区别。测试时其他条件是否都一样？截图速度主要和屏幕分辨率、内存速度、CPU、以及操作系统GDI实现有关。

**Comment by lbensaad** [comment]
Does winrobot work on XP?

**Comment by caoym** [comment]
@lbensaad, yes, it does

**Comment by Anudorannador** [comment]
所有测试条件都一样，因为用的是同一台计算机测试的，除了操作系统，一个是 win 7，另一个是 win xp …… 所以问题很有可能出在 GDI 实现有关？

**Comment by caoym** [comment]
@Anudorannador，有可能。另外xp下winrobot会启用dx7 hook，以支持directshow窗口的截屏，可能会影响性能，虽然win7上也是也启用了，但win7一般是dx9以上版本，所以hook实际没起作用，可以尝试把Hook禁用试试，需修改代码。
